In [2]:
import numpy as np

# Slide 8
myonedim = np.array(range(0,9))
print (myonedim)

# This makes an array out of a nested sequence (can be nested tuples, nested lists, or combination of them)
a = [ [[1,2],[3,4]],
      [[5,6],[7,8]],
      [[9,10],[11,12]]
     ]
print (a)
print (a[0])
print (a[0][0])
print (a[0][0][1])

[0 1 2 3 4 5 6 7 8]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]
[[1, 2], [3, 4]]
[1, 2]
2


In [5]:
# Slide 9
# Arange

import numpy as np
print (np.arange(3))
print (np.arange(3.0))
print (np.arange(3, dtype=float))
print (np.arange(3,10)) # start,stop
print (np.arange(3,10,2)) # start,stop,step

[0 1 2]
[ 0.  1.  2.]
[ 0.  1.  2.]
[3 4 5 6 7 8 9]
[3 5 7 9]


In [6]:
# Slide 9
# Linspace
print (np.linspace(2.0, 3.0, num=5))
print (np.linspace(2.0, 3.0, num=5, endpoint=False))
print (np.linspace(2.0, 3.0, num=5, retstep=True))

# Logspace
print (np.logspace(0,4,5))
np.set_printoptions(suppress=True)
print (np.logspace(0,4,5))

[ 2.    2.25  2.5   2.75  3.  ]
[ 2.   2.2  2.4  2.6  2.8]
(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)
[  1.00000000e+00   1.00000000e+01   1.00000000e+02   1.00000000e+03
   1.00000000e+04]
[     1.     10.    100.   1000.  10000.]


In [6]:
np.mgrid[0:3,1:9]

array([[[0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]]])

In [7]:
# Slide 9
# Mgrid

import numpy as np
## 2 rows and 4 columns
mygrid = np.mgrid[0:2, 0:4]
grid_x, grid_y = np.mgrid[0:2, 0:4]
print (mygrid)
print (grid_x)
print (grid_y)
# Change the numbers and see what happens

[[[0 0 0 0]
  [1 1 1 1]]

 [[0 1 2 3]
  [0 1 2 3]]]
[[0 0 0 0]
 [1 1 1 1]]
[[0 1 2 3]
 [0 1 2 3]]


In [8]:
# Slide 9
# Random
from numpy import random
# uniform random numbers in [0,1]
print (random.rand(2,5))
 
# standard normal distributed random numbers
print (random.randn(5,2))

[[ 0.12142823  0.54692257  0.56432998  0.55711965  0.28380755]
 [ 0.27592885  0.43099015  0.3020297   0.47455306  0.15008443]]
[[-0.37393792  0.60155364]
 [-0.51906444 -0.88018302]
 [-0.2935401  -1.38536614]
 [ 0.60904856  0.23644585]
 [ 1.05873595 -0.47734517]]


In [9]:
# Slide 9
import numpy as np

# a diagonal matrix
print (np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [10]:
# Slide 9
import numpy as np

# diagonal with offset from main diagonal
print (np.diag([1,2,3], k=2))

[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
# Slide 9
import numpy as np

# matrix with all zeros
print (np.zeros([3,2]))

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [12]:
# Slide 9
import numpy as np

# matrix with all ones
print (np.ones([3,3]))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [8]:
# Slide 10

# Create a csv file in spreadsheet -- mycsv.csv
# Name, Age Height
# Tom, 23, 167
# Dick, 28, 172
# Mary, 27, 168

import numpy as np 
mydata = np.loadtxt('mycsv.csv', delimiter=',', dtype=str)
print (mydata)
print (mydata.dtype)

[["b'Name'" "b'Age'" "b'Height'"]
 ["b'Tom'" "b'23'" "b'167'"]
 ["b'Dick'" "b'28'" "b'172'"]
 ["b'Mary'" "b'27'" "b'168'"]]
<U9


In [15]:
# Slide 10
# --- Another method
# Create a csv file in spreadsheet -- mycsv.csv
# Name, Age Height
# Tom, 23, 167
# Dick, 28, 172
# Mary, 27, 168

mydata = np.genfromtxt('mycsv.csv', dtype=float, delimiter=',', names=True) 
print (mydata)

[(nan, 23.0, 167.0) (nan, 28.0, 172.0) (nan, 27.0, 168.0)]


In [16]:
# Slide 10
# Another example
# Create a a csv file with ALL numbers and no headers -- myfile.csv
12,23,45
1,34,54
3,4,67

import numpy as np
# Simpler version
mydata = np.genfromtxt('myfile.csv', delimiter=',') 
print(mydata)

[[ 12.  23.  45.]
 [  1.  34.  54.]
 [  3.   4.  67.]]


In [17]:
# Slide 10
# NPY format
from numpy import random as nrand
a = nrand.randn(2,3)
np.save('myarray', a)
np.load('myarray.npy')

array([[ 1.20766104, -0.37120631,  0.33413031],
       [-0.84516614, -1.2019022 , -0.66235808]])

In [18]:
# Slide 10
# NPZ format
import numpy as np
a = np.array([[3, 2, 1], [7, 8, 9]])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.savez('myarrays.npz', a=a, b=b)
myarraydata = np.load('myarrays.npz')
print(myarraydata['a'])
print(myarraydata['b'])
myarraydata.close()

[[3 2 1]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [19]:
# Slide 16
a = np.reshape(np.arange(16),(4,4))
print (a[:2,:2])
#print (a[1:3,1:3])
#print (a[2:,2:])

[[0 1]
 [4 5]]


In [25]:
# Slide 17
import numpy as np
a = np.reshape(np.arange(12),(4,3))
print(a)
# for row sums
for r in range(a.shape[0]):
    print (sum(a[r,:]))
# for column sums
for r in range(a.shape[1]):
    print (sum(a[:,r]))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3
12
21
30
18
22
26


In [26]:
# Slide 19
import numpy as np
y = np.zeros((2, 3, 4))
print(y)
y.shape

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


(2, 3, 4)

In [9]:
# Slide 19
x = np.array([[1, 2],
              [3, 4],
              [5, 6]
             ]) 
print (x)
print (x.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [27]:
# Slide 20
import numpy as np
a = np.array(range(9))
b = a.reshape(3,3)
print (b)
print(b.diagonal())
print(b.diagonal(offset=1))
print(b.diagonal(offset=-1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]
[3 7]


In [28]:
# Slide 22
# Dot product is like matrix multiplication
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
print (np.dot(a, b))

# Ref http://cs.brown.edu/courses/cs053/current/slides/The_Matrix-6.pdf

# Inner product with vectors
a = np.array([1,2,3])
b = np.array([0,1,0])
print (np.inner(a, b))

# Inner product with arrays
a = np.arange(6).reshape((2,3))
b = np.arange(3)
print (np.inner(a, b))

# Outer product
a = [1, 2]
b = [1, 2, 3]
print (np.outer(a, b))

[[4 1]
 [2 2]]
2
[ 5 14]
[[1 2 3]
 [2 4 6]]


In [29]:
# Slide 25
import numpy as np
from scipy import linalg
A = np.array([[1,2],[3,4]])
print(A)
print (linalg.inv(A))
print (A.dot(linalg.inv(A))) #double check

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   0.00000000e+00]
 [  8.88178420e-16   1.00000000e+00]]


In [31]:
# Slide 30
import numpy as np
from numpy.linalg import inv
A = np.matrix([[1,2,3],[0,2,4],[0,0,3]])
Ainv = inv(A)
print(A)
b = np.matrix([[2],[1],[4]])
print (b)
x = Ainv*b
print (x)

[[1 2 3]
 [0 2 4]
 [0 0 3]]
[[2]
 [1]
 [4]]
[[ 2.33333333]
 [-2.16666667]
 [ 1.33333333]]


In [33]:
# Slide 31
import numpy as np
A = np.matrix([[1,2,3],[0,2,4],[0,0,3]])
print (A)
b = np.matrix([[2],[1],[4]])
print (b)
x = A.I*b
print (x)

[[1 2 3]
 [0 2 4]
 [0 0 3]]
[[2]
 [1]
 [4]]
[[ 2.33333333]
 [-2.16666667]
 [ 1.33333333]]


In [33]:
# Slide 36
# Using arrays
import numpy as np
xi = [3,2,8,5,2,6,3,7,5,3]
y=[6,3,11,6,3,9,4,12,7,5]
ones = [1]*len(xi)
X = np.concatenate(([ones],[xi]),axis=0).transpose()
# Alternatively we can use the zip function
# X = np.array(list(zip(ones, xi)))
XTX = np.dot(X.T,X)
XTXinv = np.linalg.inv(XTX)
XTy = np.dot(X.T,y)
b = np.dot(XTXinv, XTy)
b

array([ 0.32673267,  1.42574257])

In [43]:
import numpy as np
x=np.diag([1,3])
type(x)
x=np.asmatrix(x)
type(x)
b=x.I*x
b

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [34]:
# Slide 36
# Using matrices
import numpy as np
xi = [3,2,8,5,2,6,3,7,5,3]
y = [6,3,11,6,3,9,4,12,7,5]
ones = [1]*len(xi)
X = np.concatenate(([ones],[xi]),axis=0).transpose()
# Alternatively we can use the zip function
# X = np.array(list(zip(ones, xi)))
X = np.matrix(X)
y = np.reshape(y,(10,1))
b = (X.T*X).I*X.T*y
b

matrix([[ 0.32673267],
        [ 1.42574257]])